variables:
  UV_IMAGE: "ghcr.io/astral-sh/uv:python3.14-alpine"
  UV_LINK_MODE: copy

unit-test:
  image: $UV_IMAGE
  script:
    - cd project/images/web-service/
    - echo "Installing dependencies and running tests..."
    - uv sync
    - uv run pytest -v tests/test_unit.py
